openapi: 3.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /users:
    get:
      summary: /users
      description: add 'Authorization: Bearer token' to your header
      security:
        - bearerAuth: []
      responses: 
        200:  
          description: a token
          content: 
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        401:
          description: Unauthorized 
          content: 
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: This Token is not valid, please relogin
      tags: []
  /users/login:
    post:
      summary: /users/login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
              example:  
                user:
                  username: ExampleUserName
                  password: ExamplePassword
      responses:
        200:  
          description: A user object
          content: 
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        401:
          description: Unauthorized 
          content: 
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: username password combination is not correct 
      tags: []
  /users/logout:
    get:
      summary: /users/logout
      description: add 'Authorization: Bearer token' to your header
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: a token
          content:
            application/json:
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: This Token is not valid, please relogin
  /users/register:
    post:
      summary: /users/register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
              example:  
                user:
                  username: ExampleUserName
                  password: ExamplePassword
      responses:
        200:  
          description: A user object
          content: 
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        403:
          description: Forbidden
          content: 
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: This username is already used 
      tags: []
  /offer:
    get:
      summary: /offer
      description: add 'Authorization: Bearer token' to your header
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: a token and
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  data:
                    type: object
                    properties:
                      offerlist:
                        type: array
                        items:
                          type: object
                          properties:
                            _name:
                              type: string
                            _description:
                              type: string
                            _size:
                              type: double
                            _brand:
                              type: string
                            _price:
                              type: double
                            _condition:
                              type: string
                            _created:
                              type: date
                            _ownerName:
                              type: string
                            _id:
                              type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
                  data:
                    offerlist:
                        _id: 5fbf7bebcbf13743fa6ded41,
                        _name: Testoffer1,
                        _description: New Offer,
                        _price: 9.1,
                        _size: 7,
                        _brand: Nike,
                        _condition: New,
                        _ownerName: TestUser,
                        _created: 2020-11-26T09:56:59.929Z,
        403:
          description: no Ressource found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: no Ressource found
      tags: [ ]
    post:
      summary: /offer
      description: add 'Authorization: Bearer token' to your header
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                offer:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                    size:
                      type: double
                    brand:
                      type: string
                    price:
                      type: double
                    condition:
                      type: string
              example:
                user:
                  name: gread Sneaker
                  description: look nice
                  size: 9.5
                  brand: Nike
                  price: 125
                  condition: New
      responses:
        200:
          description: a token and
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                example:
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        400:
          description: creation was not succesfull
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
                example:
                  errorDescription: Sorry something went wrong. Please try it agai
      tags: [ ]
tags: []
info:
  title: Sneakerverse api-documentation
  version: 0.0.0
  description: 'Documentation:'
